### ISSUE TITLE
Horror game bugs...

### ISSUE THREAD

**Issue by Ieduun** [SennaM/Aurorea#7]
Je kan als je dood gaat en dan op esc drukt en er weer uit gaat, dan kan je weer opnieuw verder lopen met ''YOU DIED'' nog in beeld...

**Comment by Ieduun** [comment]
goed genederlandst

**Comment by TTekar** [comment]
> Je kan als je dood gaat en dan op esc drukt en er weer uit gaat, dan kan je weer opnieuw verder lopen met ''YOU DIED'' nog in beeld...

me is gonna fix
